import discord
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from discord import app_commands
from discord.ext import commands
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from services.llm_client import (
    run_ai_audit, 
    run_war_strategy, 
    run_ai_screen, 
    run_ai_scout,
    run_ai_opponent,
    run_ai_report
)
from services.coc_client import CoCClient
from services.db import get_db
from models import ServerConfig

class AICog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.coc = CoCClient()

    def get_clan_tag(self, guild_id):
        db = get_db()
        try:
            config = db.query(ServerConfig).filter(ServerConfig.guild_id == str(guild_id)).first()
            return config.clan_tag if config else None
        finally:
            db.close()

    def _generate_war_chart(self, clan_name, opp_name, clan_stars, opp_stars, clan_dest, opp_dest):
        """Membuat visual Grafik Perbandingan Bintang & Destruksi menggunakan Matplotlib"""
        fig, ax1 = plt.subplots(figsize=(6, 2.5), dpi=150)

        categories = [f"{clan_name[:10]} (Kita)", f"{opp_name[:10]} (Lawan)"]
        stars = [clan_stars, opp_stars]
        destruct = [clan_dest, opp_dest]

        x = range(len(categories))
        width = 0.35

        color_stars = '#4CAF50'
        color_dest = '#FF9800'

        rects1 = ax1.bar([p - width/2 for p in x], stars, width, label='Bintang (⭐)', color=color_stars)
        
        ax2 = ax1.twinx()
        rects2 = ax2.bar([p + width/2 for p in x], destruct, width, label='Destruksi (%)', color=color_dest, alpha=0.7)

        ax1.set_ylabel('Bintang', color=color_stars, fontweight='bold')
        ax2.set_ylabel('Destruksi %', color=color_dest, fontweight='bold')
        ax1.set_xticks(x)
        ax1.set_xticklabels(categories, fontweight='bold')

        # Nilai di atas bar
        for rect in rects1:
            height = rect.get_height()
            ax1.annotate(f'{height}⭐', xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=8, fontweight='bold')

        for rect in rects2:
            height = rect.get_height()
            ax2.annotate(f'{height:.1f}%', xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=8, fontweight='bold')

        plt.title("METRICS PERBANDINGAN PERANG", fontsize=10, fontweight='bold', pad=10)
        fig.tight_layout()

        chart_buffer = io.BytesIO()
        plt.savefig(chart_buffer, format='png')
        plt.close(fig)
        chart_buffer.seek(0)
        return chart_buffer

    async def send_as_pdf(self, interaction: discord.Interaction, title: str, text: str, chart_buf=None):
        """Membuat & mengirim PDF profesional dengan Header, Visual Chart, dan Layout Rapi"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'HeaderTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=4
        )

        sub_style = ParagraphStyle(
            'HeaderSub',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=12
        )

        body_style = ParagraphStyle(
            'BodyTextCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=colors.HexColor('#334155'),
            spaceAfter=6
        )

        story = []

        # 1. HEADER DOKUMEN
        clean_title = title.replace('_', ' ').upper()
        story.append(Paragraph(f"IXIERA EXECUTIVE REPORT: {clean_title}", title_style))
        story.append(Paragraph("Generated by Niki CoC AI Intelligence System • ixiera.id", sub_style))
        story.append(Spacer(1, 6))

        # 2. SISIPKAN GRAFIK VISUAL (JIKA ADA)
        if chart_buf:
            img = Image(chart_buf, width=420, height=175)
            story.append(img)
            story.append(Spacer(1, 12))

        # 3. KONTEN DOKUMEN
        content_table_data = []
        for line in text.split('\n'):
            line_str = line.strip()
            if not line_str:
                continue
            safe_line = line_str.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            
            if safe_line.isupper() and len(safe_line) < 40:
                # Judul Bagian / Sub-header
                p = Paragraph(f"<b><font color='#0F172A'>{safe_line}</font></b>", body_style)
            else:
                p = Paragraph(safe_line, body_style)
            content_table_data.append([p])

        if content_table_data:
            t = Table(content_table_data, colWidths=[520])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
                ('PADDING', (0,0), (-1,-1), 8),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story.append(t)

        doc.build(story)
        buffer.seek(0)

        filename = f"{title.replace(' ', '_').lower()}.pdf"
        discord_file = discord.File(fp=buffer, filename=filename)

        embed = discord.Embed(
            title=f"📊 Dokumen AI Pro: {clean_title}",
            description="Laporan analitis visual siap diunduh dalam format PDF di bawah ini.",
            color=discord.Color.gold()
        )
        embed.set_footer(text="ixiera.id — Operating System Studio | WA: https://wa.me/6285736048626")
        await interaction.followup.send(embed=embed, file=discord_file)

    async def _get_smart_war_data(self, clan_tag: str):
        try:
            war_data = await self.coc.get_current_war(clan_tag)
            if war_data and isinstance(war_data, dict) and war_data.get('state') in ['inWar', 'preparation']:
                return war_data
        except Exception:
            pass

        try:
            cwl_group = await self.coc.get_cwl_group(clan_tag)
            if cwl_group and isinstance(cwl_group, dict) and cwl_group.get('state') != 'notInWar':
                rounds = cwl_group.get('rounds', [])
                prep_war = None
                for r in reversed(rounds):
                    for w_tag in r.get('warTags', []):
                        if w_tag == '#0': continue
                        cwl_war = await self.coc.get_cwl_war(w_tag)
                        if cwl_war and isinstance(cwl_war, dict):
                            t1 = cwl_war.get('clan', {}).get('tag')
                            t2 = cwl_war.get('opponent', {}).get('tag')
                            
                            if t1 == clan_tag or t2 == clan_tag:
                                if t2 == clan_tag:
                                    cwl_war['clan'], cwl_war['opponent'] = cwl_war['opponent'], cwl_war['clan']
                                state = cwl_war.get('state')
                                if state == 'inWar':
                                    return cwl_war
                                elif state == 'preparation' and not prep_war:
                                    prep_war = cwl_war
                if prep_war:
                    return prep_war
        except Exception:
            pass
        return None

    async def _get_latest_finished_war(self, clan_tag: str):
        try:
            cwl_group = await self.coc.get_cwl_group(clan_tag)
            if cwl_group and isinstance(cwl_group, dict) and cwl_group.get('state') != 'notInWar':
                rounds = cwl_group.get('rounds', [])
                for r in reversed(rounds):
                    for w_tag in r.get('warTags', []):
                        if w_tag == '#0': continue
                        cwl_war = await self.coc.get_cwl_war(w_tag)
                        if cwl_war and isinstance(cwl_war, dict) and cwl_war.get('state') == 'warEnded':
                            t1 = cwl_war.get('clan', {}).get('tag')
                            t2 = cwl_war.get('opponent', {}).get('tag')
                            if t1 == clan_tag or t2 == clan_tag:
                                if t2 == clan_tag:
                                    cwl_war['clan'], cwl_war['opponent'] = cwl_war['opponent'], cwl_war['clan']
                                return cwl_war
        except Exception:
            pass
            
        war_logs = await self.coc.get_war_log(clan_tag)
        if war_logs and isinstance(war_logs, list) and len(war_logs) > 0:
            return war_logs[0]
        return None

    @app_commands.command(name="ai-audit", description="[AI PRO] Audit kesehatan klan & evaluasi member (Cetak PDF)")
    async def ai_audit(self, interaction: discord.Interaction):
        await interaction.response.defer()
        result = await run_ai_audit(str(interaction.guild_id))
        await self.send_as_pdf(interaction, "Audit_Kesehatan_Klan", result)

    @app_commands.command(name="war-strategy", description="[AI PRO] Taktik agregat rotasi attack CWL/War (Cetak PDF + Grafik)")
    async def ai_war_strategy(self, interaction: discord.Interaction):
        await interaction.response.defer()
        clan_tag = self.get_clan_tag(interaction.guild_id)
        if not clan_tag:
            return await interaction.followup.send("❌ Server belum di-setup!")
            
        war_data = await self._get_smart_war_data(clan_tag)
        result = await run_war_strategy(str(interaction.guild_id), war_data)

        # Generate Chart Visual jika data war tersedia
        chart_buf = None
        if war_data and isinstance(war_data, dict):
            c = war_data.get('clan', {})
            o = war_data.get('opponent', {})
            chart_buf = self._generate_war_chart(
                c.get('name', 'Kita'), o.get('name', 'Lawan'),
                c.get('stars', 0), o.get('stars', 0),
                c.get('destructionPercentage', 0.0), o.get('destructionPercentage', 0.0)
            )

        await self.send_as_pdf(interaction, "Strategi_Perang_Aktif", result, chart_buf=chart_buf)

    @app_commands.command(name="ai-report", description="[AI PRO] Evaluasi performa member & MVP pasca CWL/War (Cetak PDF + Grafik)")
    async def ai_report(self, interaction: discord.Interaction):
        await interaction.response.defer()
        clan_tag = self.get_clan_tag(interaction.guild_id)
        if not clan_tag:
            return await interaction.followup.send("❌ Server belum di-setup!")
            
        latest_war = await self._get_latest_finished_war(clan_tag)
        if not latest_war:
            return await interaction.followup.send("❌ Tidak ada data perang atau CWL yang baru saja selesai.")
            
        result = await run_ai_report(str(interaction.guild_id), latest_war)

        chart_buf = None
        if latest_war and isinstance(latest_war, dict):
            c = latest_war.get('clan', {})
            o = latest_war.get('opponent', {})
            chart_buf = self._generate_war_chart(
                c.get('name', 'Kita'), o.get('name', 'Lawan'),
                c.get('stars', 0), o.get('stars', 0),
                c.get('destructionPercentage', 0.0), o.get('destructionPercentage', 0.0)
            )

        await self.send_as_pdf(interaction, "Laporan_Evaluasi_Pasca_Perang", result, chart_buf=chart_buf)

    @app_commands.command(name="ai-screen", description="[AI PRO] Intel profil calon member sebelum di-acc (Cetak PDF)")
    @app_commands.describe(player_tag="Tag player calon member (cth: #ABC1234)")
    async def ai_screen(self, interaction: discord.Interaction, player_tag: str):
        await interaction.response.defer()
        if not player_tag.startswith('#'):
            player_tag = f"#{player_tag}"
        player_data = await self.coc.get_player_info(player_tag)
        if not player_data or 'tag' not in player_data:
            return await interaction.followup.send("❌ Data player tidak ditemukan!")
        result = await run_ai_screen(str(interaction.guild_id), player_data)
        await self.send_as_pdf(interaction, f"Screening_Member_{player_data.get('name')}", result)

    @app_commands.command(name="ai-scout", description="[AI PRO] Intel CWL/War lawan: cari target base terlemah (Cetak PDF)")
    async def ai_scout(self, interaction: discord.Interaction):
        await interaction.response.defer()
        clan_tag = self.get_clan_tag(interaction.guild_id)
        if not clan_tag:
            return await interaction.followup.send("❌ Server belum di-setup!")
        war_data = await self._get_smart_war_data(clan_tag)
        if not war_data or war_data.get('state') not in ['inWar', 'preparation']:
            return await interaction.followup.send("❌ Clan sedang tidak dalam periode War atau CWL aktif!")
        result = await run_ai_scout(str(interaction.guild_id), war_data)
        await self.send_as_pdf(interaction, "Scouting_Target_Lawan", result)

    @app_commands.command(name="ai-opponent", description="[AI PRO] Estimasi peluang menang vs klan lawan (Cetak PDF)")
    async def ai_opponent(self, interaction: discord.Interaction):
        await interaction.response.defer()
        clan_tag = self.get_clan_tag(interaction.guild_id)
        if not clan_tag:
            return await interaction.followup.send("❌ Server belum di-setup!")
        war_data = await self._get_smart_war_data(clan_tag)
        if not war_data or war_data.get('state') not in ['inWar', 'preparation']:
            return await interaction.followup.send("❌ Clan sedang tidak dalam periode War atau CWL aktif!")
        result = await run_ai_opponent(str(interaction.guild_id), clan_tag, war_data)
        await self.send_as_pdf(interaction, "Estimasi_Peluang_Menang", result)

async def setup(bot):
    await bot.add_cog(AICog(bot))
